[pytest]
# Default discovery and report options for this project.
testpaths = script
python_files = test_01_register.py test_02_login.py test_03_open_account.py test_04_loan_amount_apply.py test_05_admin_login.py test_06_admin_amount_apply_audit.py
python_functions = test_*
addopts = -s -v
markers =
    login: login module tests
    register: register module tests
    open_account: open account module tests
    loan_amount_apply: loan amount apply tests
    admin_login: admin login module tests
    admin_amount_apply_audit: admin amount apply audit tests
